version: 2

updates:
  - package-ecosystem: npm
    directory: /apps/frontend
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - frontend

  - package-ecosystem: pip
    directory: /apps/backend
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - backend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: /apps/frontend
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /apps/backend
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
